{attribute 'pack_mode' := '1'} 
// ------------------------------------------------------------------------- 
//  SRCI Robot Library                                                
// ------------------------------------------------------------------------- 
//                                                                           
//  Object:      ArmConfigParameter                                       
//  Author:      Thorsten Brach                                                
//  Date:        2024-06-01
//
//  Description:                                              
//   
//                                                                           
//  Copyright: 
//    (C) 2024 Thorsten Brach. All rights reserved                                                                                                                                            
//             Licensed under the LGPL-3.0 license.
//                                                                           
//  Disclaimer:                                                                           
//    This project is provided without any guarantee and can be used for   
//    private and commercial purposes. Any use is at the user’s 
//    own risk and responsibility.
//
// -------------------------------------------------------------------------
TYPE ArmConfigParameter :
STRUCT
  /// Configuration of shoulder
  Shoulder : ArmConfigShoulder;
  /// Configuration of elbow
  Elbow    : ArmConfigElbow;
  /// Configuration of wrist
  Wrist    : ArmConfigWrist;
END_STRUCT
END_TYPE


