{attribute 'pack_mode' := '1'} 
// ------------------------------------------------------------------------- 
//  SRCI Robot Library                                                
// ------------------------------------------------------------------------- 
//                                                                           
//  Object:      ReadMessagesParCmd                                       
//  Author:      Thorsten Brach                                                
//  Date:        2024-08-09
//
//  Description:                                              
//   
//                                                                           
//  Copyright: 
//    (C) 2024 Thorsten Brach. All rights reserved                                                                                                                                            
//             Licensed under the LGPL-3.0 license.
//                                                                           
//  Disclaimer:                                                                           
//    This project is provided without any guarantee and can be used for   
//    private and commercial purposes. Any use is at the user’s 
//    own risk and responsibility.
//
// -------------------------------------------------------------------------
TYPE ReadMessagesParCmd :
STRUCT
  /// ID for function specific acknowledgement mechanism
  MsgID        : USINT;
  /// TRUE when function is returning messages from RC
  Enable       : BOOL;
  /// Defines up to which level of severity messages will be transmitted to the PLC’s message buffer
  MessageLevel : MessageLevel;
END_STRUCT
END_TYPE


